name: Auto Update Submodules

on:
  schedule:
    - cron: "0 */8 * * *"
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PA_TOKEN }}
          persist-credentials: true
          submodules: recursive

      - name: Make script executable
        run: chmod +x ./script.sh

      - name: Run update script
        run: ./script.sh
